name: dynamic_list_view
description: A list component that can refreshes and adds more data for Flutter App.
version: 0.2.0
authors:
  - leyan95 <leyansorosame@gmail.com>
homepage: https://github.com/leyan95/dynamic_list_view

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shinow.dynamic_list_view
    pluginClass: DynamicListViewPlugin
